spring:
  cache:
    type: caffeine
    cache-names: weatherCache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=15m

resilience4j:
  circuitbreaker:
    instances:
      weatherApi:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      weatherApi:
        maxAttempts: 3
        waitDuration: 2s


stormglass:
  api-key: ${STORMGLAS_API_KEY:c1c2b5d8-25e8-11f1-8cf9-0242ac120003-c1c2b63c-25e8-11f1-8cf9-0242ac120003}
server:
  port: 8085