spring:
  cache:
    type: caffeine
    cache-names: weatherCache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=15m

resilience4j:
  circuitbreaker:
    instances:
      weatherApi:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      weatherApi:
        maxAttempts: 3
        waitDuration: 2s


stormglass:
  url: https://api.stormglass.io
  api-key: ${STORMGLASS_API_KEY:c1c2b5d8-25e8-11f1-8cf9-0242ac120003-c1c2b63c-25e8-11f1-8cf9-0242ac120003}

openweather:
  url: https://api.openweathermap.org
  api-key: ${OPENWEATHER_API_KEY:b200b025f997945e387b1a669bbab685}
server:
  port: 8085