services:
  db:
    image: postgres:15
    container_name: lab-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./ApiGateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
    depends_on:
      - auth-service

  auth-service:
    build: ./AuthService
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lab

volumes:
  postgres_data: